version: '3'

services:
  db:
    image: mysql:5.5
    container_name: mysql-db
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql
      - .:/web-app
    environment:
      MYSQL_ROOT_PASSWORD: dbs123
      MYSQL_DATABASE: mariadb
      MYSQL_USER: user
      MYSQL_PASSWORD: dbs123

  web-app:
    build: .
    container_name: web-app
    command: bundle exec rails s -p 5050 -b '0.0.0.0'
    volumes:
      - .:/web-app
      - web_rubygems:/usr/local/bundle 
    ports:
      - "5050:5050"
    depends_on:
      - db
    tty: true 
    stdin_open: true

  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/opt/dockerrailsdemo:cached
    ports:
      - 3035:3035
volumes:
  db_data:
  web_rubygems: